exclude: "docs|node_modules|migrations|.git|dist"
default_stages: [pre-commit, pre-push]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
      - id: eslint
        files: ^frontend/
        types: [file]
        types_or: [javascript, jsx, ts, tsx]
        additional_dependencies:
          - eslint@9.0.0
          - eslint-config-standard
          - eslint-plugin-import
          - eslint-plugin-n
          - eslint-plugin-promise
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - eslint-plugin-react
          - eslint-plugin-react-hooks

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, css, scss, json, yaml]
        additional_dependencies:
          - prettier@3.1.0

ci:
  autofix_commit_msg: "chore: auto fixes from pre-commit hooks"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
